---
title: 
output: 
  flexdashboard::flex_dashboard:
    theme: simplex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load libraries}

library(flexdashboard)
library(dplyr)
library(knitr)
library(kableExtra)
library(plotly)
library(formattable)
library(readxl)
library(DT)
library(lubridate)
library(chron)
library(ggplot2)
library(vistime)
library(scales)
library(tidyverse)

```

Budget {data-navmenu="financials"}
===================================== 


```{r table}
tables <- function(x){

x %>% select(1:5) %>% mutate(total = paste("EUR", format(round(total, 2L),nsmall = 2,big.mark = ","))) %>% 
  kable(
   format = "html", escape = F) %>% kable_styling(fixed_thead =   T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black")  %>% 
  column_spec(1, width = "8em") %>% 
  column_spec(5,bold = TRUE, width = "8em")}
```


_**Grupo Pharma Barcelona**_ {data-width=850}
-------------------------------------------

<br><br>

```{r budget_table}

budget <- read_excel("rooming.xlsx", sheet = "bud", range = "B13:F24") 
budget <- sapply(budget, as.character)
budget[is.na(budget)] <- ""
budget <- data.frame(budget, stringsAsFactors = FALSE)
class(budget$bud_units) <- "numeric"
class(budget$bud_cost) <- "numeric"
class(budget$bud_total) <- "numeric"

names(budget) <- c("description","units","unit cost","total")


budget[nrow(budget),] <- c("","","<strong>Total</strong>","",sum(budget$total),"")

class(budget$total) <- "numeric"

tables(budget)

```

